=== DebasishMaji/Conan2/conan-core-services/src/main/resources/conan/pipelines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.ebi.ac.uk/arrayexpress/conan/pipelines"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.ebi.ac.uk/arrayexpress/conan/pipelines">
    <xsd:element name="conan-pipelines" type="conan-pipelinesType"/>

    <xsd:element name="pipeline" type="pipelineType"/>

    <xsd:element name="processes" type="processesType"/>

    <xsd:element name="process" type="processType"/>

    <xsd:complexType name="conan-pipelinesType">
        <xsd:sequence>
            <xsd:element ref="pipeline" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="pipelineType">
        <xsd:sequence>
            <xsd:element ref="processes"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" use="required"/>
        <xsd:attribute type="xsd:string" name="creator" use="required"/>
        <xsd:attribute type="xsd:boolean" name="daemonized" use="optional" default="false"/>
        <xsd:attribute type="xsd:boolean" name="private" use="optional" default="false"/>
    </xsd:complexType>

    <xsd:complexType name="processesType">
        <xsd:sequence>
            <xsd:element ref="process" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="processType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="name" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== DebasishMaji/Conan2/conan-ae2-processes/src/main/resources/conan/pipelines.xml
<?xml version="1.0" encoding="UTF-8"?>

<conan-pipelines xmlns="http://www.ebi.ac.uk/arrayexpress/conan/pipelines"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.ebi.ac.uk/arrayexpress/conan/pipelines
                                     http://www.ebi.ac.uk/arrayexpress/conan/pipelines.xsd">

    <!--
    Add xml elements to name your pipeline and chain processes together here
    Note that the interface will display these pipelines in declaration order, with the first pipeline as the default
    -->

    <!-- AE2 processes -->
    <pipeline name="AE2 Experiment Loading" creator="natalja" daemonized="false">
        <processes>
            <process name="validation" />
            <process name="experiment loading" />
            <process name="scoring" />
            <process name="afterloading" />
        </processes>
    </pipeline>

    <pipeline name="AE2 Experiment Unloading" creator="natalja">
        <processes>
            <process name="experiment unloading" />
        </processes>
    </pipeline>

    <pipeline name="AE2 ADF Loading" creator="natalja">
        <processes>
            <process name="validation" />
            <process name="adf loading" />
            <process name="scoring" />
            <process name="afterloading" />
            <!--<process name="adf reannotation" />-->
        </processes>
    </pipeline>

    <pipeline name="AE2 ADF Unloading" creator="natalja">
        <processes>
            <process name="adf unloading" />
        </processes>
    </pipeline>

</conan-pipelines>

=== DebasishMaji/Conan2/conan-biosd-processes/src/main/resources/conan/pipelines.xml
<?xml version="1.0" encoding="UTF-8"?>

<conan-pipelines xmlns="http://www.ebi.ac.uk/arrayexpress/conan/pipelines"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.ebi.ac.uk/arrayexpress/conan/pipelines
                                     http://www.ebi.ac.uk/arrayexpress/conan/pipelines.xsd">
    
    <pipeline name="BioSamples (other)" creator="faulcon">
        <processes>
            <process name="accessionsampletab" displayName="accession sampletab.pre.txt" />
            <process name="toloadsampletab" displayName="to sampletab.toload.txt" />
            <process name="toguixml" displayName="to GUI XML" />
            <process name="toftp" displayName="copy to FTP site" />
<!--             <process name="sampletabmyequivalents" displayName="to MyEquivalents" /> -->
<!--             <process name="sampletabrelationalloader" displayName="to relational DB" /> -->
        </processes>
    </pipeline>
    
    <pipeline name="BioSamples make public" creator="faulcon">
        <processes>
            <process name="toftp" displayName="copy to FTP site" />
            <process name="makepublic" displayName="make public in AGE db" />
        </processes>
    </pipeline>
    
    <pipeline name="BioSamples make non-public" creator="faulcon">
        <processes>
            <process name="removeftp" displayName="remove from FTP site" />
            <process name="makenonpublic" displayName="make non-public in AGE db" />
        </processes>
    </pipeline>
    
    <pipeline name="Test performance" creator="faulcon">
        <processes>
            <process name="delay" displayName="do nothing for 60 seconds" />
        </processes>
    </pipeline>
</conan-pipelines>

=== DebasishMaji/Conan2/conan-ae1-processes/src/main/resources/conan/pipelines.xml
<?xml version="1.0" encoding="UTF-8"?>

<conan-pipelines xmlns="http://www.ebi.ac.uk/arrayexpress/conan/pipelines"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.ebi.ac.uk/arrayexpress/conan/pipelines
                                     http://www.ebi.ac.uk/arrayexpress/conan/pipelines.xsd">

    <!--
    Add xml elements to name your pipeline and chain processes together here
    Note that the interface will display these pipelines in declaration order, with the first pipeline as the default
    -->
    <!--AE2 and AE1 combined processes-->
    <pipeline name="Experiment Loading (Combined AE2/AE1)" creator="natalja">
        <processes>
            <process name="validation for AE2" />
            <process name="experiment loading for AE2" />
            <process name="scoring for AE2" />
            <process name="afterloading for AE2" />
            <process name="AE1 Validate" />
            <process name="AE1 Load" />
            <process name="AE1 Afterload" />
            <process name="AE1 Archive" />
            <process name="AE1 QM Calculation" />
        </processes>
    </pipeline>

    <pipeline name="ADF Loading (Combined AE2/AE1)" creator="natalja">
        <processes>
            <process name="validation for AE2" />
            <process name="adf loading for AE2" />
            <process name="scoring for AE2" />
            <process name="afterloading for AE2" />
            <process name="AE1 Validate" />
            <process name="AE1 Load" />
            <process name="AE1 Afterload" />
            <process name="AE1 Archive" />
        </processes>
    </pipeline>
    <!-- AE1 processes -->
    <pipeline name="AE1 Loading" creator="natalja">
        <processes>
            <process name="AE1 Validate" />
            <process name="AE1 Load" />
            <process name="AE1 Afterload" />
            <process name="AE1 Archive" />
            <process name="AE1 QM Calculation" />
        </processes>
    </pipeline>

    <pipeline name="AE1 Loading with insert" creator="natalja">
        <processes>
            <process name="AE1 Validate with insert" />
            <process name="AE1 Load with insert" />
            <process name="AE1 Afterload" />
            <process name="AE1 Archive" />
        </processes>
    </pipeline>

    <pipeline name="AE1 Postloading" creator="natalja">
        <processes>
            <process name="AE1 Postload" />
        </processes>
    </pipeline>

    <pipeline name="AE1 Unloading" creator="natalja">
        <processes>
            <process name="AE1 Unload" />
        </processes>
    </pipeline>

</conan-pipelines>

=== DebasishMaji/Conan2/conan-core-services/src/test/resources/conan/pipelines.xml
<?xml version="1.0" encoding="UTF-8"?>

<conan-pipelines xmlns="http://www.ebi.ac.uk/arrayexpress/conan/pipelines"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.ebi.ac.uk/arrayexpress/conan/pipelines
                                     http://www.ebi.ac.uk/arrayexpress/conan/pipelines.xsd">

    <!--
    Add xml elements to name your pipeline and chain processes together here
    Note that the interface will display these pipelines in declaration order, with the first pipeline as the default
    -->

    <!--<pipeline name="Experiment loading" creator="natalja" daemonized="true">-->
    <!--<processes>-->
    <!--<process name="Validation process"/>-->
    <!--</processes>-->
    <!--</pipeline>-->

    <!--<pipeline name="ADF loading" creator="natalja" daemonized="true">-->
    <!--<processes>-->
    <!--<process name="Validation process"/>-->
    <!--<process name="ADF loading process"/>-->
    <!--</processes>-->
    <!--</pipeline>-->

    <!-- demo pipeline -->
    <pipeline name="demo pipeline" creator="tburdett">
        <processes>
            <process name="demo process"/>
        </processes>
    </pipeline>

    <pipeline name="demo pipeline (many processes)" creator="tburdett">
        <processes>
            <process name="demo process"/>
            <process name="demo process"/>
            <process name="demo process"/>
            <process name="demo process"/>
            <process name="demo process"/>
            <process name="demo process"/>
            <process name="demo process"/>
        </processes>
    </pipeline>

    <pipeline name="demo pipeline (lsf)" creator="tburdett">
        <processes>
            <process name="demo process (executes on LSF)"/>
            <process name="demo process"/>
            <process name="demo process (executes on LSF)"/>
            <process name="demo process"/>
        </processes>
    </pipeline>

    <!-- demo pipeline, many params -->
    <pipeline name="demo pipeline (5 params)" creator="tburdett">
        <processes>
            <process name="demo process"/>
            <process name="demo process (5 parameters)"/>
        </processes>
    </pipeline>

    <!-- demo pipeline, process 2 fails -->
    <pipeline name="demo pipeline (always fails)" creator="tburdett">
        <processes>
            <process name="demo process"/>
            <process name="demo process (always fails)"/>
        </processes>
    </pipeline>

</conan-pipelines>

=== DebasishMaji/Conan2/conan-atlas-processes/src/main/resources/conan/pipelines.xml
<?xml version="1.0" encoding="UTF-8"?>

<conan-pipelines xmlns="http://www.ebi.ac.uk/arrayexpress/conan/pipelines"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.ebi.ac.uk/arrayexpress/conan/pipelines
                                     http://www.ebi.ac.uk/arrayexpress/conan/pipelines.xsd">

    <!--
    Add xml elements to name your pipeline and chain processes together here
    Note that the interface will display these pipelines in declaration order, with the first pipeline as the default
    -->

    <!-- AE2 processes -->
    <pipeline name="Experiment Loading (Combined AE2/Atlas)" creator="natalja" daemonized="true">
        <processes>
            <process name="validation" />
            <process name="experiment loading" />
            <process name="scoring" />
            <process name="afterloading" />
            <process name="atlas validation" />
            <process name="atlas loading" />
        </processes>
    </pipeline>

    <pipeline name="Atlas Experiment Unloading" creator="natalja">
        <processes>
            <process name="atlas unloading" />
        </processes>
    </pipeline>

    <pipeline name="Atlas Experiment Private" creator="natalja">
        <processes>
            <process name="atlas private" />
        </processes>
    </pipeline>

    <pipeline name="Atlas Experiment Public" creator="natalja">
        <processes>
            <process name="atlas public" />
        </processes>
    </pipeline>

</conan-pipelines>
